package Vista;

import Controlador.ControladorInventario;
import Modelo.Producto;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Controlador.ControladorInventario;
import Modelo.Producto;

/**
 *
 * @author 
 */
public class UIPrincipal extends javax.swing.JFrame {

    // CAMBIO MVC: en lugar de usar ArchivoInventario directo, usamos el Controlador
    ControladorInventario controlador;
    DefaultTableModel modelo;

    public UIPrincipal() throws IOException {
        initComponents();
        controlador = new ControladorInventario("inventario.dat");
        modelo = new DefaultTableModel(new String[]{"ID", "Nombre", "Desc", "Exist", "Estado"}, 0);
        this.tblProductos.setModel(modelo);
        this.listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnReporte = new javax.swing.JButton();
        panelTabla = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        panelFormulario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ABARROTES LOS PRIMOS");
        panelTitulo.add(jLabel1);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        btnGuardar.setText("GUARDAR");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        panelBotones.add(btnGuardar);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        panelBotones.add(btnEliminar);

        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });
        panelBotones.add(btnActualizar);

        btnReporte.setText("REPORTE");
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReporteMouseClicked(evt);
            }
        });
        panelBotones.add(btnReporte);

        getContentPane().add(panelBotones, java.awt.BorderLayout.PAGE_END);

        panelTabla.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripción", "Precio", "Existencia"
            }
        ));
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblProductos);

        panelTabla.add(jScrollPane2);

        getContentPane().add(panelTabla, java.awt.BorderLayout.CENTER);

        java.awt.GridBagLayout panelFormularioLayout = new java.awt.GridBagLayout();
        panelFormularioLayout.columnWidths = new int[] {0, 6, 0, 6, 0, 6, 0};
        panelFormularioLayout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0};
        panelFormulario.setLayout(panelFormularioLayout);

        jLabel2.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(jLabel2, gridBagConstraints);

        txtId.setColumns(5);
        txtId.setPreferredSize(new java.awt.Dimension(100, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(txtId, gridBagConstraints);

        jLabel3.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(jLabel3, gridBagConstraints);

        txtNombre.setColumns(15);
        txtNombre.setPreferredSize(new java.awt.Dimension(100, 22));
        txtNombre.addActionListener(this::txtNombreActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(txtNombre, gridBagConstraints);

        jLabel4.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(jLabel4, gridBagConstraints);

        txtDescripcion.setColumns(30);
        txtDescripcion.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 3.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(txtDescripcion, gridBagConstraints);

        jLabel6.setText("Existencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(jLabel6, gridBagConstraints);

        txtExistencia.setName("txtExistencia"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelFormulario.add(txtExistencia, gridBagConstraints);

        btnBuscar.setText("BUSCAR");
        btnBuscar.setName("btnBuscar"); // NOI18N
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        panelFormulario.add(btnBuscar, gridBagConstraints);

        getContentPane().add(panelFormulario, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void listar() {
        try {
            modelo.setRowCount(0);
            int total = controlador.totalRegistros();
            for (int i = 0; i < total; i++) {
                Producto p = controlador.leer(i);
                if (p != null && p.estado) {
                    modelo.addRow(new Object[]{p.id, p.nombre, p.descripcion, p.existencia, p.estado});
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        // TODO add your handling code here:
        try {
            controlador.guardar(
                    Integer.parseInt(txtId.getText()),
                    txtNombre.getText(),
                    txtDescripcion.getText(),
                    Integer.parseInt(txtExistencia.getText())
            );
            listar();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        try {
            int fila = this.tblProductos.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para eliminar.");
                return;
            }

            // Obtener el ID de la fila visual de la tabla
            int idEliminar = Integer.parseInt(this.tblProductos.getValueAt(fila, 0).toString());

            // El Controlador busca su posición exacta en el archivo .dat y hace el borrado lógico
            controlador.eliminar(idEliminar);

            listar(); // Refrescar tabla visual
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
        // TODO add your handling code here:
        try {
            int fila = this.tblProductos.getSelectedRow();
            if (fila == -1) {
                JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla para actualizar.");
                return;
            }

            // Obtener el ID original del registro seleccionado antes de que el usuario lo edite en los inputs
            int idOriginal = Integer.parseInt(this.tblProductos.getValueAt(fila, 0).toString());

            // El Controlador busca el índice físico en el archivo y sobreescribe
            controlador.actualizar(
                    idOriginal,
                    Integer.parseInt(txtId.getText()),
                    txtNombre.getText(),
                    txtDescripcion.getText(),
                    Integer.parseInt(txtExistencia.getText())
            );

            listar();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseClicked
        // TODO add your handling code here:
        try {
            controlador.mostrarReporte(this);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnReporteMouseClicked

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductosMouseClicked
        // TODO add your handling code here:
        int fila = this.tblProductos.getSelectedRow();

        if (fila == -1) {
            return;
        }

        try {
            // ... Todo tu código de búsqueda que pusimos antes ...
            int idSeleccionado = Integer.parseInt(this.tblProductos.getValueAt(fila, 0).toString());
            int total = controlador.totalRegistros();
            for (int i = 0; i < total; i++) {
                Producto p = controlador.leer(i);
                if (p != null && p.estado && p.id == idSeleccionado) {
                    txtId.setText(String.valueOf(p.id));
                    txtNombre.setText(p.nombre);
                    txtDescripcion.setText(p.descripcion);
                    txtExistencia.setText(String.valueOf(p.existencia));
                    break;
                }
            }

        } catch (IOException ex) {
            // REEMPLAZA LA LÍNEA DEL ERROR POR ESTA:
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tblProductosMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        if (this.txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID para buscar.");
            return;
        }

        try {
            int idBuscar = Integer.parseInt(this.txtId.getText().trim());
            int filasTabla = this.tblProductos.getRowCount(); // Obtenemos cuántas filas hay REALMENTE en la tabla

            // 2. Recorremos la tabla visual fila por fila
            for (int i = 0; i < filasTabla; i++) {
                int idEnTabla = Integer.parseInt(this.tblProductos.getValueAt(i, 0).toString());

                // 3. Si el ID coincide con el que buscamos
                if (idBuscar == idEnTabla) {
                    // Llenamos los campos de texto con los datos de esa fila de la tabla
                    txtNombre.setText(this.tblProductos.getValueAt(i, 1).toString());
                    txtDescripcion.setText(this.tblProductos.getValueAt(i, 2).toString());
                    txtExistencia.setText(this.tblProductos.getValueAt(i, 3).toString());

                    // Seleccionamos visualmente la fila encontrada
                    this.tblProductos.setRowSelectionInterval(i, i);
                    return; // Terminamos el método exitosamente
                }
            }

            // Si termina el ciclo y no entró al 'if', significa que no existe o está eliminado (false)
            JOptionPane.showMessageDialog(this, "No se encuentra el registro activo con ese ID");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new UIPrincipal().setVisible(true);
            } catch (IOException ex) {
                System.getLogger(UIPrincipal.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnReporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
