package vista;

import controlador.ControladorRegistrarEstudiante;

public class VistaRegistrarEstudiante extends javax.swing.JFrame {

    VistaMenuPrincipal menu;
    ControladorRegistrarEstudiante ctlRegConEst;

    public VistaRegistrarEstudiante(VistaMenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        this.ctlRegConEst = new ControladorRegistrarEstudiante(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNumControl = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCarrera = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();
        txtNumControl = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cboCarrera = new javax.swing.JComboBox<>();
        txtApellidos = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        cboSemestre = new javax.swing.JComboBox<>();
        cboGrupo = new javax.swing.JComboBox<>();
        jLabelCarrera1 = new javax.swing.JLabel();
        jLabelCarrera2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(204, 204, 204));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel1.setText("REGISTRAR ESTUDIANTE");
        bgPanelConsulta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 450, 40));

        jLabelNumControl.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelNumControl.setText("Num. Control:");
        bgPanelConsulta.add(jLabelNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabelNombre.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        bgPanelConsulta.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabelCarrera.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelCarrera.setText("Carrera:");
        bgPanelConsulta.add(jLabelCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jLabelPromedio.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelPromedio.setText("Apellidos:");
        bgPanelConsulta.add(jLabelPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));
        bgPanelConsulta.add(txtNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 250, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 250, -1));

        cboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingeniería en Agronomía", "Licenciatura en Biología", "Ingeniería Forestal", "Ingeniería Informática", "Ingeniería en Tecnologías de la Información y Comunicaciones", "Ingeniería en Ciencia de Datos", "Ingeniería Ambiental", "Ingeniería en Gestión Empresarial" }));
        bgPanelConsulta.add(cboCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 250, -1));
        bgPanelConsulta.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 250, -1));

        btnGuardar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 490, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, 30));

        cboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));
        bgPanelConsulta.add(cboSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 250, -1));

        cboGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        bgPanelConsulta.add(cboGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 250, -1));

        jLabelCarrera1.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelCarrera1.setText("Semestre:");
        bgPanelConsulta.add(jLabelCarrera1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jLabelCarrera2.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelCarrera2.setText("Grupo:");
        bgPanelConsulta.add(jLabelCarrera2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        this.guardarRegistro();        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cboCarrera;
    private javax.swing.JComboBox<String> cboGrupo;
    private javax.swing.JComboBox<String> cboSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCarrera;
    private javax.swing.JLabel jLabelCarrera1;
    private javax.swing.JLabel jLabelCarrera2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumControl;
    private javax.swing.JLabel jLabelPromedio;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumControl;
    // End of variables declaration//GEN-END:variables

    private void guardarRegistro() {

    this.ctlRegConEst.registrarEstudiante(
            this.txtNumControl.getText(),
            this.txtNombre.getText(),
            this.txtApellidos.getText(),
            this.cboSemestre.getSelectedItem().toString(),
            this.cboGrupo.getSelectedItem().toString(),
            this.cboCarrera.getSelectedItem().toString()
    );

    this.limpiarCajas();
}

    private void limpiarCajas() {
        this.txtNumControl.setText("");
        this.txtApellidos.setText("");
        this.txtNombre.setText("");
        this.cboSemestre.setSelectedIndex(0);
        this.cboGrupo.setSelectedIndex(0);
        this.cboCarrera.setSelectedIndex(0);


    }

}
