package vista;
import controlador.ControladorConsultarEstudiante;

public class VistaConsultarEstudiante extends javax.swing.JFrame {
    VistaMenuPrincipal menu;
    ControladorConsultarEstudiante ctlConEst;
    
    public VistaConsultarEstudiante(VistaMenuPrincipal menu) {
        initComponents();
        this.menu = menu;
        this.ctlConEst = new ControladorConsultarEstudiante(this);
            this.listarEstudiante();        // TODO add your handling code here:

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanelConsulta = new javax.swing.JPanel();
        jLabelTituloRegtrEst = new javax.swing.JLabel();
        btnListar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(204, 204, 204));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloRegtrEst.setFont(new java.awt.Font("Cinzel Black", 1, 36)); // NOI18N
        jLabelTituloRegtrEst.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloRegtrEst.setText("LISTAR ESTUDIANTE");
        bgPanelConsulta.add(jLabelTituloRegtrEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 770, -1));

        btnListar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnListar.setText("LISTAR");
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        btnRegresar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        bgPanelConsulta.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Control", "Nombre", "Apellidos", "Semestre", "Grupo", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEstudiantes);

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 750, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
    menu.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarMouseClicked
    this.listarEstudiante();        // TODO add your handling code here:
    }//GEN-LAST:event_btnListarMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabelTituloRegtrEst;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tblEstudiantes;
    // End of variables declaration//GEN-END:variables

    
    private void listarEstudiante(){
        String[] columnas = {"Num. Control", "Nombre", "Apellidos","Semestre", "Grupo", "Carrera"};                      
        this.ctlConEst.listarEst(columnas);  
            
    }
    
    
}
