package clases;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaInventario extends javax.swing.JFrame {
    private ArchivoInventario archivo = new ArchivoInventario();
    private DefaultTableModel modelo;
    
    public static void main(String[] args) {
        VistaInventario objViewContact = new VistaInventario();
        objViewContact.setVisible(true);
    }
    
    
    public VistaInventario() {
        initComponents();
        modelo = new DefaultTableModel();
        cargarTabla();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Descripción");
        modelo.addColumn("Existencia");
        
        tblDatos.setModel(modelo);
        cargarTabla();
        this.txtId.requestFocus();
        
        this.btnEliminar.setEnabled(false);
        this.btnModificar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        bgPanelConsulta = new javax.swing.JPanel();
        jLabelId = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        txtDescripcion = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabeTituloAgenda = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnBuscar1 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        bgPanelConsulta.setBackground(new java.awt.Color(204, 204, 204));
        bgPanelConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelId.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelId.setText("ID");
        bgPanelConsulta.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelTelefono.setText("Nombre");
        bgPanelConsulta.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelEmail.setText("Descripción");
        bgPanelConsulta.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, -1));
        bgPanelConsulta.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        btnAgregar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 130, -1));

        btnEliminar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 130, -1));

        tblDatos.setAutoCreateRowSorter(true);
        tblDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDatos);
        if (tblDatos.getColumnModel().getColumnCount() > 0) {
            tblDatos.getColumnModel().getColumn(0).setResizable(false);
        }

        bgPanelConsulta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 620, 300));
        bgPanelConsulta.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabeTituloAgenda.setBackground(new java.awt.Color(0, 0, 0));
        jLabeTituloAgenda.setFont(new java.awt.Font("Arial Black", 1, 41)); // NOI18N
        jLabeTituloAgenda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabeTituloAgenda.setText("Inventario Centro Computo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabeTituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabeTituloAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bgPanelConsulta.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 110));

        jLabelEmail1.setFont(new java.awt.Font("Belleza", 0, 14)); // NOI18N
        jLabelEmail1.setText("Existencia");
        bgPanelConsulta.add(jLabelEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));
        bgPanelConsulta.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 240, -1));

        btnModificar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 130, -1));

        btnBuscar.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 130, -1));

        btnBuscar1.setFont(new java.awt.Font("Chau Philomene One", 0, 14)); // NOI18N
        btnBuscar1.setText("LISTAR");
        btnBuscar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscar1MouseClicked(evt);
            }
        });
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });
        bgPanelConsulta.add(btnBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bgPanelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
    Producto p = new Producto(
            Integer.parseInt(txtId.getText()),
            txtNombre.getText(),
            txtDescripcion.getText(),
            Integer.parseInt(txtExistencia.getText())
        );

        archivo.agregar(p);
        cargarTabla();
        limpiarCajas();
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
    eliminarProducto();
    limpiarCajas();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
    modificarProducto();
    limpiarCajas();
 // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {                                     

    int id = Integer.parseInt(txtId.getText());

    Producto p = archivo.buscar(id);

    if (p != null) {

        txtNombre.setText(p.getNombre());
        txtDescripcion.setText(p.getDescripcion());
        txtExistencia.setText(String.valueOf(p.getExistencia()));

        for (int i = 0; i < tblDatos.getRowCount(); i++) {

            int idTabla = Integer.parseInt(
                tblDatos.getValueAt(i, 0).toString()
            );

            if (idTabla == id) {

                tblDatos.setRowSelectionInterval(i, i);
                break;
            }
        }

        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnAgregar.setEnabled(false);

    } else {

        JOptionPane.showMessageDialog(this,
            "No encontrado");
    }
}                                      

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscar1MouseClicked
        cargarTabla();
    }//GEN-LAST:event_btnBuscar1MouseClicked

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanelConsulta;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabeTituloAgenda;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

  
    
   private void mostrarProductos() {
    cargarTabla();
    }
    private void limpiarCajas(){
    txtId.setText("");
    txtNombre.setText("");
    txtDescripcion.setText("");
    txtExistencia.setText("");
    }

    private void guardarProducto() {
        Producto p = new Producto(
            Integer.parseInt(txtId.getText()),
            txtNombre.getText(),
            txtDescripcion.getText(),
            Integer.parseInt(txtExistencia.getText()));

}
    
    private void cargarTabla() {
    modelo.setRowCount(0);
    ArrayList<Producto> lista = archivo.leerTodos();
    for (Producto p : lista) {
        if (p.isEstado()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getNombre(),
                p.getDescripcion(),
                p.getExistencia()
            });
        }
    }
    }
    
    private void eliminarProducto() {
    int fila = tblDatos.getSelectedRow();

    if (fila != -1) {
        int id = (int) modelo.getValueAt(fila, 0);
        archivo.eliminar(id);
        cargarTabla();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila");
    }
    
        }
    
    private void limpiarTabla() {
        modelo.setRowCount(0);
    }

    
    
    
    private void modificarProducto() {
    int fila = tblDatos.getSelectedRow();

    if (fila != -1) {
        int id = (int) modelo.getValueAt(fila, 0);

        try {
            String nombre = txtNombre.getText();
            String desc = txtDescripcion.getText();
            int existencia = Integer.parseInt(txtExistencia.getText());

            archivo.modificar(id, nombre, desc, existencia);
            cargarTabla();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error en datos");
        }

    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila");
    }
        }
    
    
}
